apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: registry.toolz.homelabz.eu/library/cks-frontend
    newTag: f8bcc38ba974638c844b1d79ed085f2099bb0e54

patches:
  - patch: |-
      - op: replace
        path: /spec/hosts/0
        value: "cks.homelabz.eu"
    target:
      kind: VirtualService
      name: cks-frontend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Rollout
      name: cks-frontend
  - patch: |-
      - op: remove
        path: /spec/strategy/blueGreen/prePromotionAnalysis
    target:
      kind: Rollout
      name: cks-frontend
  - patch: |-
      - op: remove
        path: /spec/strategy/blueGreen/postPromotionAnalysis
    target:
      kind: Rollout
      name: cks-frontend
configMapGenerator:
  - name: cks-frontend-config
    behavior: merge
    envs:
      - configmap
