apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cks-frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  hosts:
    - "dev.cks.homelabz.eu"   # Will be overridden in overlays
  gateways:
    - istio-system/default-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: cks-frontend.default.svc.cluster.local
            port:
              number: 3000
