apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: registry.toolz.homelabz.eu/library/cks-frontend
    newTag: 4af5bbf56a9afd64dcd5dd2fb5dd5d3560bca36b

configMapGenerator:
  - name: cks-frontend-config
    behavior: merge
    envs:
      - configmap
