apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: registry.toolz.homelabz.eu/library/cks-frontend
    newTag: e28392809f50deaa62bb16b175c1aa787296355c

configMapGenerator:
  - name: cks-frontend-config
    behavior: merge
    envs:
      - configmap
